[character]
symbol = "❭"
vicmd_symbol = "❬"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[line_break]
disabled = true

[memory_usage]
disabled = false
threshold = 75
symbol = ""
style = "bold dimmed yellow"

# Remove unnecessary text in prompt
[cmd_duration]
format = "[$duration]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""

[nodejs]
format = "[$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "📦"

[php]
format = "[$symbol$version]($style) "
symbol = "P"

[python]
format = "[$symbol$version]($style) "
symbol = "P"

[rust]
format = "[$symbol$version]($style) "
symbol = "R"

[java]
disabled = true
