#!/usr/bin/env bash

pkill sxhkd || true
SXHKD_SHELL=sh sxhkd &

if ! pidof picom > /dev/null; then
    picom --experimental-backends &
fi
if ! pidof dunst > /dev/null; then
    dunst &
fi
if ! pidof xss-lock > /dev/null; then
    xss-lock ~/.config/bspwm/lockscreen &
fi
if ! pidof pasystray > /dev/null; then
    pasystray &
fi
if ! pidof nm-applet > /dev/null; then
    nm-applet &
fi
if ! pidof blueman-applet > /dev/null; then
    blueman-applet &
fi

~/.config/polybar/launch.sh &

# MONITORS
for m in $(xrandr | grep ' connected' | awk '{ print $1 }'); do
    bspc monitor $m -d home code edit im music game sys bullshit
done

#### BSPWM configuration ####
window_gap=4
bspc config border_width                    1
bspc config window_gap                      $window_gap
bspc config top_padding                     $((20 - window_gap))
bspc config bottom_padding                  0
bspc config left_padding                    0
bspc config right_padding                   0
bspc config top_monocle_padding             0
bspc config bottom_monocle_padding          0
bspc config left_monocle_padding            0
bspc config right_monocle_padding           0
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config single_monocle                  true
bspc config click_to_focus                  any
bspc config ignore_ewmh_focus               true
bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_follows_pointer           false
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true
bspc config merge_overlapping_monitors      true
bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		        "#4c566a"
bspc config active_border_color	            "#1e1e1e"
bspc config focused_border_color	        "#5e81ac"
bspc config presel_feedback_color	        "#5e81ac"
bspc config urgent_border_color 	        "#dd2727"

#### BSPWM rules ####
bspc rule -a Firefox desktop='^1'
bspc rule -a Nightly desktop='^1'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a MellowPlayer desktop='^5' follow=on
bspc rule -a Mumble desktop='^4' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^6' follow=false
bspc rule -a mplayer2 state=floating

# Battlefield 1 / Origin
bspc rule -a Origin state=floating
bspc rule -a steam_app_1182480 state=floating

#### OTHER STUFF ####

# Use regular cursor on desktop
xsetroot -cursor_name left_ptr

# Set wallpaper
feh --bg-fill ~/.config/bspwm/wallpaper.jpg
