#!/usr/bin/env bash

if ! pidof sxhkd >/dev/null; then
    set -U SXHKD_SHELL sh
    sxhkd &
fi
if ! pidof compton >/dev/null; then
    compton &
fi
if ! pidof dunst >/dev/null; then
    dunst &
fi
if ! pidof xss-lock >/dev/null; then
    xss-lock ~/.config/bspwm/lockscreen &
fi
if ! pidof pasystray >/dev/null; then
    pasystray &
fi
if ! pidof nm-applet >/dev/null; then
    nm-applet &
fi

~/.config/polybar/launch.sh &

# MONITORS
bspc monitor -d home code edit im music game sys bullshit

#### BSPWM configuration ####
# bspc config border_radius                 8
window_gap=4
bspc config border_width                    1
bspc config window_gap                      $window_gap
bspc config top_padding                     $((24 - window_gap))
bspc config bottom_padding                  $((4  - window_gap))
bspc config left_padding                    $((4  - window_gap))
bspc config right_padding                   $((4  - window_gap))
bspc config top_monocle_padding             0
bspc config bottom_monocle_padding          0
bspc config left_monocle_padding            0
bspc config right_monocle_padding           0
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config single_monocle                  true
bspc config click_to_focus                  any
bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_by_distance               true
bspc config focus_follows_pointer           false
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true
bspc config merge_overlapping_monitors      true
bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc config normal_border_color           "#454948" #Unfocused windows
bspc config active_border_color           "#555A59" #Focused window on unfocused monitor
bspc config focused_border_color          "#9498A3" #Focused window
bspc config presel_feedback_color         "#9394FE" #Preselect area color

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-2)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### OTHER STUFF ####

# Use regular cursor on desktop
xsetroot -cursor_name left_ptr

# Set wallpaper
feh --bg-fill ~/.config/bspwm/wallpaper.jpg
