#!/bin/bash
# Purge/removes old revisions of snaps
#
# CLOSE ALL SNAPS BEFORE RUNNING THIS
#
# Script from: https://www.linuxuprising.com/2019/04/how-to-remove-old-snap-versions-to-free.html

set -eu

LANG=en_US.UTF-8 snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
