#!/bin/bash

# Run given command when given file is changed
#
# Example:
# ```
# ./runonchange test.txt echo File has changed!
# ```

watch=$1
cmd="${@:2}"

while true; do
    echo
    echo "# Running $cmd..."

    $cmd

    sleep 0.5
    inotifywait -qre attrib $watch > /dev/null
    sleep 0.5
done
