# ~/.bash_aliases: executed by bash for alias configurations.

# Grep aliases
alias grep='grep --color=auto'
alias grepi='grep -i --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Shell exit alias
alias q='exit'
alias :q='exit'

# Nvim and vim aliases
if [[ $(command -v nvim) ]]; then
    alias v='nvim'
    alias vi='nvim'
    alias vim='nvim'
    alias nvi='nvim'
else
    alias v='vim'
    alias vi='vim'
    alias nvi='vim'
fi

# Eza/exa elias
if [[ $(command -v nvim) ]]; then
    alias e='eza'
    alias ela='eza -lab --git'
else
    alias e='exa'
    alias ela='exa -lab --git'
fi

# Useful list aliases
alias la='ls -al'

# Ranger alias
alias r='ranger'

# Tmux alias
alias tmux='tmux -u -2'
alias tl='tmux -u -2 ls'
function ta {
    tmux -u -2 attach $@ || tmux -u -2
}
function tn {
    tmux -u -2 new -s $@ || tmux -u -2
}

# Make a directory and change to it
function mkcd {
    # Make the directory
    mkdir $@

    # Change to the newly created directory
    cd $@
}

# Pass aliases
alias p="prs show --verbose --timeout 20"
alias pc="prs copy"

# Git aliases
alias g='git'
alias ga='git add'
alias ga.='git add .'
alias gap='git add --patch'
alias gapn='git add --intent-to-add . && git add --patch'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias gl='git log'
alias gll="git -c core.pager='less -p^commit.*$' log -p -M -w --stat --pretty=fuller --show-notes"
alias glg='git log --pretty="format:%Cred%h %Cblue%d %Cgreen%s %Creset%an %ar" --graph'
alias gf='git fetch'
alias gfm='git pull'
alias gr='git rebase'
alias grc='git rebase --continue'
alias grr='git reset'
alias grrh='git reset --hard'
alias gt='git tag'
alias git_clean_repo='git clean -dfx'

# Docker aliases
alias d='docker'
alias dc='docker-compose'

# Make alias
alias m='make'

# Clipboard aliases
if [[ `uname -s` == "Darwin" ]]; then
    alias getclip='pbpaste'
    alias setclip='pbcopy'
else
    alias getclip='xclip -selection c -o'
    alias setclip='xclip -selection c'
fi

# Cargo aliases
alias cr='cargo run'
alias crr='cargo run --release'
alias cb='cargo build'
alias cbr='cargo build --release'
alias cc='cargo check'
alias ct='cargo test'
alias cu='cargo update'

# Free memory cache and swap
alias drop_cache='sudo sh -c "echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a"'

# Add an "alert" alias for long running commands.
# Usage example: $ sleep 5; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Thefuck aliases
if [ -e "/usr/bin/thefuck" ]; then
    eval "$(thefuck --alias)"
fi

# Create the composer alias if it exists
if [ -e "/usr/local/bin/composer.phar" ]; then
    alias composer="php /usr/local/bin/composer.phar"
fi

# Aliases to hide and show hidden files on macOS
if [[ `uname -s` == "Darwin" ]]; then
    alias showFiles='echo "Showing files..."; defaults write com.apple.finder AppleShowAllFiles YES; sleep 1; killall Finder; /System/Library/CoreServices/Finder.app; echo "Done"'
    alias hideFiles='echo "Hiding files..."; defaults write com.apple.finder AppleShowAllFiles NO; sleep 1; killall Finder /System/Library/CoreServices/Finder.app; echo "Done"'
fi

alias stripcolors='sed "s/\x1B\[\([0-9]\{1,2\}\(;[0-9]\{1,2\}\)\?\)\?[mGK]//g"'
