# ~/.bash_profile: executed by bash for profiled shells.

# Source the .bashrc file if it exists
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# NVM configuration
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
