# ~/.bash_profile: executed by bash for profiled shells.

# Clear keychain passwords on login
[[ -n `which keychain` ]] && keychain --clear --noask

# Add PATHs
export PATH="$HOME/.cargo/bin:$PATH"

# Source .bashrc
[ -f ~/.bashrc ] && . ~/.bashrc

# nvm configuration
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
