# ~/.bash_aliases: executed by bash for alias configurations.

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Shell exit alias
alias q='exit'
alias :q='exit'

# Nvim and vim aliases
if [[ $(command -v nvim) ]]; then
    alias vi='nvim'
    alias vim='nvim'
    alias nvi='nvim'
else
    alias vi='vim'
    alias nvi='vim'
fi

# Exa elias
alias e='exa'
alias ela='exa -lab --git'

# Useful list aliases
alias la='ls -al'

# Ranger alias
alias r='ranger'

# Tmux alias
alias tmux='tmux -u -2'
alias ta='tmux -u -2 attach'
alias tl='tmux -u -2 ls'
alias tn='tmux -u -2 new -s'

# Make a directory and change to it
function mkcd {
    # Make the directory
    mkdir $@

    # Change to the newly created directory
    cd $@
}

# Git aliases
alias g='git'
alias ga='git add'
alias gap='git add --patch'
alias gapn='git add --intent-to-add . && git add --patch'
alias gb='git branch'
alias gc='git commit'
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias gl='git log'
alias gf='git fetch'
alias gfp='git fetch && git pull'

# Clipboard aliases
alias getclip='xclip -selection c -o'
alias setclip='xclip -selection c'

# Cargo aliases
alias cr='cargo run'
alias crr='cargo run --release'
alias cb='cargo build'
alias cbr='cargo build --release'
alias cc='cargo check'
alias ct='cargo test'

# Add an "alert" alias for long running commands.
# Usage example: $ sleep 5; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Thefuck aliases
if [ -e "/usr/bin/thefuck" ]; then
    eval "$(thefuck --alias)"
fi

# Create the composer alias if it exists
if [ -e "/usr/local/bin/composer.phar" ]; then
    alias composer="php /usr/local/bin/composer.phar"
fi

# Aliases to hide and show hidden files on macOS
case "$(uname)" in
    "Darwin")
        alias showFiles='echo "Showing files..."; defaults write com.apple.finder AppleShowAllFiles YES; sleep 1; killall Finder; /System/Library/CoreServices/Finder.app; echo "Done"'
        alias hideFiles='echo "Hiding files..."; defaults write com.apple.finder AppleShowAllFiles NO; sleep 1; killall Finder /System/Library/CoreServices/Finder.app; echo "Done"'
esac
